"""update users table

Revision ID: 21f24d0b87c8
Revises: b90cbe5090c1
Create Date: 2025-02-04 23:36:54.073905

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21f24d0b87c8"
down_revision: Union[str, None] = "b90cbe5090c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.create_unique_constraint(
        op.f("uq_users_username"), "users", ["username"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.create_unique_constraint("users_username_key", "users", ["username"])
    # ### end Alembic commands ###
