"""add route_id to dashboard_configurations

Revision ID: 8902cf6e5270
Revises: 5e06737f8b29
Create Date: 2025-05-11 22:09:42.555328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8902cf6e5270"
down_revision: Union[str, None] = "5e06737f8b29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_dashboards_category", table_name="dashboards")
    op.drop_index("ix_dashboards_creator_id", table_name="dashboards")
    op.drop_index("ix_dashboards_dashboard_name", table_name="dashboards")
    op.drop_table("dashboards")
    op.add_column(
        "dashboard_configurations",
        sa.Column("route_id", sa.String(), nullable=True),
    )
    op.create_index(
        op.f("ix_dashboard_configurations_route_id"),
        "dashboard_configurations",
        ["route_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dashboard_configurations_route_id"),
        table_name="dashboard_configurations",
    )
    op.drop_column("dashboard_configurations", "route_id")
    op.create_table(
        "dashboards",
        sa.Column(
            "dashboard_id", sa.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "dashboard_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "dashboard_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "creator_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "creator_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "category",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tags",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("dashboard_id", name="pk_dashboards"),
    )
    op.create_index(
        "ix_dashboards_dashboard_name",
        "dashboards",
        ["dashboard_name"],
        unique=False,
    )
    op.create_index(
        "ix_dashboards_creator_id", "dashboards", ["creator_id"], unique=False
    )
    op.create_index(
        "ix_dashboards_category", "dashboards", ["category"], unique=False
    )
    # ### end Alembic commands ###
