"""create dashboards_configuration table

Revision ID: 5e06737f8b29
Revises: 9b3767fcecdb
Create Date: 2025-04-29 18:54:11.088131

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e06737f8b29"
down_revision: Union[str, None] = "9b3767fcecdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("graphs", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_dashboard_configurations")
        ),
    )
    op.create_index(
        op.f("ix_dashboard_configurations_id"),
        "dashboard_configurations",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dashboard_configurations_id"),
        table_name="dashboard_configurations",
    )
    op.drop_table("dashboard_configurations")
    # ### end Alembic commands ###
