"""Create initial tables for sources, cache and history

Revision ID: 92d9bb2671cb
Revises: df006c7dd8ae
Create Date: 2025-04-27 14:53:27.579520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "92d9bb2671cb"
down_revision: Union[str, None] = "df006c7dd8ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "predefined_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("available_filters", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predefined_sources")),
    )
    op.create_index(
        op.f("ix_predefined_sources_id"),
        "predefined_sources",
        ["id"],
        unique=False,
    )
    op.create_table(
        "query_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query_hash", sa.String(), nullable=False),
        sa.Column("result_json", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_query_cache")),
    )
    op.create_index(
        op.f("ix_query_cache_id"), "query_cache", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_query_cache_query_hash"),
        "query_cache",
        ["query_hash"],
        unique=True,
    )
    op.create_table(
        "query_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("executed_query", sa.Text(), nullable=False),
        sa.Column(
            "executed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("rows_returned", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_query_history")),
    )
    op.create_index(
        op.f("ix_query_history_id"), "query_history", ["id"], unique=False
    )
    op.drop_index("ix_dashboards_access_groups", table_name="dashboards")
    op.drop_index("ix_dashboards_access_user_ids", table_name="dashboards")
    op.drop_column("dashboards", "access_groups")
    op.drop_column("dashboards", "access_user_ids")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dashboards",
        sa.Column(
            "access_user_ids",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "dashboards",
        sa.Column(
            "access_groups",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "admin", "analyst", "hr", name="accessgrouprole"
                )
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        "ix_dashboards_access_user_ids",
        "dashboards",
        ["access_user_ids"],
        unique=False,
    )
    op.create_index(
        "ix_dashboards_access_groups",
        "dashboards",
        ["access_groups"],
        unique=False,
    )
    op.drop_index(op.f("ix_query_history_id"), table_name="query_history")
    op.drop_table("query_history")
    op.drop_index(op.f("ix_query_cache_query_hash"), table_name="query_cache")
    op.drop_index(op.f("ix_query_cache_id"), table_name="query_cache")
    op.drop_table("query_cache")
    op.drop_index(
        op.f("ix_predefined_sources_id"), table_name="predefined_sources"
    )
    op.drop_table("predefined_sources")
    # ### end Alembic commands ###
