"""create metabase_dashboards table

Revision ID: 399f32e1e9a9
Revises: ea46d67b37d5
Create Date: 2025-04-22 23:05:10.560542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "399f32e1e9a9"
down_revision: Union[str, None] = "ea46d67b37d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboards",
        sa.Column("dashboard_id", sa.Integer(), nullable=False),
        sa.Column("dashboard_name", sa.String(), nullable=False),
        sa.Column("dashboard_url", sa.String(length=500), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("creator_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("access_user_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column(
            "access_groups",
            sa.ARRAY(
                sa.Enum("admin", "analyst", "hr", name="accessgrouprole")
            ),
            nullable=True,
        ),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("dashboard_id", name=op.f("pk_dashboards")),
    )
    op.create_index(
        op.f("ix_dashboards_access_groups"),
        "dashboards",
        ["access_groups"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dashboards_access_user_ids"),
        "dashboards",
        ["access_user_ids"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dashboards_category"),
        "dashboards",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dashboards_creator_id"),
        "dashboards",
        ["creator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dashboards_dashboard_name"),
        "dashboards",
        ["dashboard_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dashboards_dashboard_name"), table_name="dashboards"
    )
    op.drop_index(op.f("ix_dashboards_creator_id"), table_name="dashboards")
    op.drop_index(op.f("ix_dashboards_category"), table_name="dashboards")
    op.drop_index(
        op.f("ix_dashboards_access_user_ids"), table_name="dashboards"
    )
    op.drop_index(op.f("ix_dashboards_access_groups"), table_name="dashboards")
    op.drop_table("dashboards")
    # ### end Alembic commands ###
